#------------------------------------------------------------------------------
# 
# Module : GamosCore_GamosGenerator
# Package: 
#
#------------------------------------------------------------------------------
set(CMAKE_VERBOSE_MAKEFILE ON)
include(Geant4MacroDefineModule)
include_directories(${CMAKE_SOURCE_DIR}/source)
#
# Define the GAMOS Module.
#
GEANT4_DEFINE_MODULE(NAME GamosCore_GamosGenerator
	 HEADERS
		GmGenerDistEnergyRandomFlat.hh
		GmVGenerDistTime.hh
		GmGeneratorFactory.hh
		GmGeneratorFromTextFile.hh
		GmGenerDistPositionVoxelPhantomMaterials.hh
		RTPlanParamReader.hh
		RTVPlanBeam.hh
		GmGenerDistDirectionConeGaussian.hh
		GmGenerEnergyDistConstant.hh
		GmGenerDistPositionInVoxelsFromFile.hh
		GmGenerDistTimeConstant.hh
		GmGeneratorMgr.hh
		GmGenerDistPositionInG4Volumes.hh
		GmVPositionOrigin.hh
		GmPositionVolumePos.hh
		GmGenerDistPositionRectangle.hh
		PrimaryGeneratorGPS.hh
		GmGeneratorFromBinFile.hh
		GmGeneratorDistributionFactories.hh
		GmGenerDistPositionDiscFromFile.hh
		GmGenerator.hh
		GmSingleParticleSource.hh
		GmGeneratorChangeEnergyAndMaterial.hh
		RTVPlanControlPoint.hh
		GmGenerDistDirectionGaussian.hh
		GmVGenerDistPosition2D.hh
		GmGeneratorIsotope.hh
		GmGenerDistEnergyFromFile.hh
		GmVGenerDistPosition.hh
		GmIsotopeSource.hh
		GmGenerDistPositionInG4Materials.hh
		GmVPositionObjectPos.hh
		GmGenerDistPositionDisc.hh
		RTIonPlanControlPoint.hh
		GmVGenerDist.hh
		GmGenerDistPositionSquare.hh
		GmGenerDistPositionLineSteps.hh
		GmGenerEnergyDistBetaDecay.hh
		GmGenerDistPositionDirectionInVolumeSurface.hh
		GmGenerDistPositionDirectionInUserSurfaces.hh
		GmGenerDistDirectionCone2DGaussian.hh
		RTIonPlanScanSpotSource.hh
		GmGenerDistPositionDirectionTowardsBox.hh
		RTPlanControlPoint.hh
		GmGenerDistEnergyConstant.hh
		GmGenerDistEnergyBetaDecay.hh
		GmGenerDistEnergyMCNPisolethargical.hh
		GmGenerDistDirectionConst.hh
		GmGeneratorMessenger.hh
		GmVGenerDistPositionVolumesAndSurfaces.hh
		GmPositionUserVolumes.hh
		GmGenerDistPositionInUserVolumes.hh
		GmIsotope.hh
		GmParticleSource.hh
		GmIsotopeMgr.hh
		GmVGenerDistDirection.hh
		RTPlanBeam.hh
		GmGenerDistPositionInG4Surfaces.hh
		GmGenerDistEnergyGaussian.hh
		GmIsotopeDecay.hh
		RTIonPlanBeam.hh
		GmGenerDistDirectionRandom.hh
		GmGenerDistEnergyConstantIsotopeDecay.hh
		RTVPlanSource.hh
		GmGenerDistEnergyIsolethargical.hh
		GmGeneratorFromFile.hh
		GmGenerDistTimeDecay.hh
		GmGenerDistTimeConstantChange.hh
		GmPositionG4Materials.hh
		RTPlanSource.hh
		GmGenerDistDirectionCone2D.hh
		RTPlanMessenger.hh
		GmGenerVerbosity.hh
		GmDoubleBackToBackParticleSource.hh
		GmPositionG4Volumes.hh
		GmGenerDistPositionInG4VolumesGeneral.hh
		GmGeneratorScanVis.hh
		GmGenerDistPositionInUserSurfaces.hh
		GmGenerDistPositionDiscGaussian.hh
		GmGenerDistPositionPoint.hh
		GmIsotopeMessenger.hh
		GmGenerDistDirectionCone.hh
		GmPositionSurfacePos.hh
		GmGenerDistDirectionThetaFromFile.hh
		GmVGenerDistEnergy.hh
		GmGenerDistWavelengthFromFile.hh
		GmGenerDistWavelengthRandomFlat.hh
	 SOURCES
		GmGenerDistDirectionConst.cc
		GmVGenerDist.cc
		GmGenerDistEnergyConstant.cc
		GmGenerDistDirectionCone.cc
		GmGenerDistPositionPoint.cc
		GmGenerDistPositionDirectionTowardsBox.cc
		GmGenerator.cc
		GmIsotope.cc
		RTVPlanSource.cc
		RTIonPlanScanSpotSource.cc
		GmGeneratorScanVis.cc
		GmDoubleBackToBackParticleSource.cc
		GmGenerDistEnergyGaussian.cc
		RTPlanControlPoint.cc
		RTPlanMessenger.cc
		GmGenerDistEnergyBetaDecay.cc
		GmGenerDistPositionInG4VolumesGeneral.cc
		RTVPlanBeam.cc
		GmIsotopeSource.cc
		RTVPlanSource.cc.1
		GmGenerDistEnergyIsolethargical.cc
		RTVPlanControlPoint.cc
		GmGenerDistDirectionGaussian.cc
		GmGeneratorMessenger.cc
		RTIonPlanBeam.cc
		PrimaryGeneratorGPS.cc
		GmGeneratorChangeEnergyAndMaterial.cc
		GmPositionVolumePos.cc
		GmGenerDistPositionDiscGaussian.cc
		GmGenerDistDirectionConeGaussian.cc
		GmPositionUserVolumes.cc
		GmGenerDistPositionDirectionInVolumeSurface.cc
		GmGenerDistPositionDirectionInUserSurfaces.cc
		GmPositionG4Volumes.cc
		GmGenerDistPositionLineSteps.cc
		GmParticleSource.cc
		GmGenerDistPositionSquare.cc
		GmGenerDistDirectionCone2DGaussian.cc
		GmGenerDistEnergyConstantIsotopeDecay.cc
		GmSingleParticleSource.cc
		GmGenerDistDirectionCone2D.cc
		GmVGenerDistPositionVolumesAndSurfaces.cc
		GmPositionSurfacePos.cc
		GmVGenerDistPosition2D.cc
		GmGenerDistEnergyFromFile.cc
		GmGeneratorFactory.cc
		GmGenerDistPositionDisc.cc
		RTPlanSource.cc
		GmGenerDistTimeConstant.cc
		RTPlanParamReader.cc
		RTIonPlanControlPoint.cc
		GmGenerDistDirectionRandom.cc
		GmGenerDistTimeDecay.cc
		GmGenerVerbosity.cc
		GmGenerDistEnergyMCNPisolethargical.cc
		GmGenerDistPositionInVoxelsFromFile.cc
		GmGeneratorMgr.cc
		GmGenerDistEnergyRandomFlat.cc
		GmGeneratorDistributionFactories.cc
		GmGenerDistPositionDiscFromFile.cc
		RTPlanBeam.cc
		GmGeneratorFromFile.cc
		GmIsotopeDecay.cc
		GmGenerDistPositionVoxelPhantomMaterials.cc
		GmGeneratorFromTextFile.cc
		GmGeneratorFromBinFile.cc
		GmPositionG4Materials.cc
		GmGenerDistTimeConstantChange.cc
		GmGenerDistDirectionThetaFromFile.cc
		GmIsotopeMgr.cc
		GmGenerDistPositionRectangle.cc
		GmGenerDistWavelengthFromFile.cc
		GmGenerDistWavelengthRandomFlat.cc
		plugin.cc
	 
	 GLOBAL_DEPENDENCIES
		${Geant4_LIBRARIES} 
		${ROOT_LIBRARIES} 
	GamosCore_GamosBase_Base
	GamosCore_GamosUtils
	GamosCore_GamosGeometry
	GamosCore_GamosUserActionMgr
	GamosCore_GamosAnalysis

	LINK_LIBRARIES
)
