# Generated by CMake 2.8.8

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target G4analysis
ADD_LIBRARY(G4analysis SHARED IMPORTED)

# Create imported target G4digits_hits
ADD_LIBRARY(G4digits_hits SHARED IMPORTED)

# Create imported target G4error_propagation
ADD_LIBRARY(G4error_propagation SHARED IMPORTED)

# Create imported target G4event
ADD_LIBRARY(G4event SHARED IMPORTED)

# Create imported target G4clhep
ADD_LIBRARY(G4clhep SHARED IMPORTED)

# Create imported target G4geometry
ADD_LIBRARY(G4geometry SHARED IMPORTED)

# Create imported target G4global
ADD_LIBRARY(G4global SHARED IMPORTED)

# Create imported target G4graphics_reps
ADD_LIBRARY(G4graphics_reps SHARED IMPORTED)

# Create imported target G4intercoms
ADD_LIBRARY(G4intercoms SHARED IMPORTED)

# Create imported target G4interfaces
ADD_LIBRARY(G4interfaces SHARED IMPORTED)

# Create imported target G4materials
ADD_LIBRARY(G4materials SHARED IMPORTED)

# Create imported target G4parmodels
ADD_LIBRARY(G4parmodels SHARED IMPORTED)

# Create imported target G4particles
ADD_LIBRARY(G4particles SHARED IMPORTED)

# Create imported target G4persistency
ADD_LIBRARY(G4persistency SHARED IMPORTED)

# Create imported target G4physicslists
ADD_LIBRARY(G4physicslists SHARED IMPORTED)

# Create imported target G4processes
ADD_LIBRARY(G4processes SHARED IMPORTED)

# Create imported target G4readout
ADD_LIBRARY(G4readout SHARED IMPORTED)

# Create imported target G4run
ADD_LIBRARY(G4run SHARED IMPORTED)

# Create imported target G4track
ADD_LIBRARY(G4track SHARED IMPORTED)

# Create imported target G4tracking
ADD_LIBRARY(G4tracking SHARED IMPORTED)

# Create imported target G4FR
ADD_LIBRARY(G4FR SHARED IMPORTED)

# Create imported target G4visHepRep
ADD_LIBRARY(G4visHepRep SHARED IMPORTED)

# Create imported target G4RayTracer
ADD_LIBRARY(G4RayTracer SHARED IMPORTED)

# Create imported target G4Tree
ADD_LIBRARY(G4Tree SHARED IMPORTED)

# Create imported target G4VRML
ADD_LIBRARY(G4VRML SHARED IMPORTED)

# Create imported target G4visXXX
ADD_LIBRARY(G4visXXX SHARED IMPORTED)

# Create imported target G4gl2ps
ADD_LIBRARY(G4gl2ps SHARED IMPORTED)

# Create imported target G4zlib
ADD_LIBRARY(G4zlib SHARED IMPORTED)

# Create imported target G4GMocren
ADD_LIBRARY(G4GMocren SHARED IMPORTED)

# Create imported target G4vis_management
ADD_LIBRARY(G4vis_management SHARED IMPORTED)

# Create imported target G4modeling
ADD_LIBRARY(G4modeling SHARED IMPORTED)

# Create imported target G4OpenGL
ADD_LIBRARY(G4OpenGL SHARED IMPORTED)

# Create imported target G4analysis
ADD_LIBRARY(GamosUtils SHARED IMPORTED)

# Import target "G4analysis" for configuration "Release"
SET_PROPERTY(TARGET G4analysis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4analysis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4global;G4intercoms"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4analysis.so"
  IMPORTED_SONAME_RELEASE "libG4analysis.so"
  )

# Import target "G4digits_hits" for configuration "Release"
SET_PROPERTY(TARGET G4digits_hits APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4digits_hits PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4geometry;G4global;G4intercoms;G4materials;G4particles;G4track;G4graphics_reps"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4digits_hits.so"
  IMPORTED_SONAME_RELEASE "libG4digits_hits.so"
  )

# Import target "G4error_propagation" for configuration "Release"
SET_PROPERTY(TARGET G4error_propagation APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4error_propagation PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4event;G4geometry;G4global;G4intercoms;G4materials;G4particles;G4processes;G4run;G4track;G4tracking"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4error_propagation.so"
  IMPORTED_SONAME_RELEASE "libG4error_propagation.so"
  )

# Import target "G4event" for configuration "Release"
SET_PROPERTY(TARGET G4event APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4event PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4processes;G4track;G4tracking"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4event.so"
  IMPORTED_SONAME_RELEASE "libG4event.so"
  )

# Import target "G4clhep" for configuration "Release"
SET_PROPERTY(TARGET G4clhep APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4clhep PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4clhep.so"
  IMPORTED_SONAME_RELEASE "libG4clhep.so"
  )

# Import target "G4geometry" for configuration "Release"
SET_PROPERTY(TARGET G4geometry APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4geometry PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4global;G4graphics_reps;G4intercoms;G4materials"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4geometry.so"
  IMPORTED_SONAME_RELEASE "libG4geometry.so"
  )

# Import target "G4global" for configuration "Release"
SET_PROPERTY(TARGET G4global APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4global PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4clhep"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4global.so"
  IMPORTED_SONAME_RELEASE "libG4global.so"
  )

# Import target "G4graphics_reps" for configuration "Release"
SET_PROPERTY(TARGET G4graphics_reps APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4graphics_reps PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4global;G4intercoms"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4graphics_reps.so"
  IMPORTED_SONAME_RELEASE "libG4graphics_reps.so"
  )

# Import target "G4intercoms" for configuration "Release"
SET_PROPERTY(TARGET G4intercoms APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4intercoms PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4global"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4intercoms.so"
  IMPORTED_SONAME_RELEASE "libG4intercoms.so"
  )

# Import target "G4interfaces" for configuration "Release"
SET_PROPERTY(TARGET G4interfaces APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4interfaces PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4global;G4intercoms;/usr/lib64/libQtGui.so;/usr/lib64/libQtCore.so;/usr/lib64/libQtCore_debug.so"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4interfaces.so"
  IMPORTED_SONAME_RELEASE "libG4interfaces.so"
  )

# Import target "G4materials" for configuration "Release"
SET_PROPERTY(TARGET G4materials APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4materials PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4global;G4intercoms"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4materials.so"
  IMPORTED_SONAME_RELEASE "libG4materials.so"
  )

# Import target "G4parmodels" for configuration "Release"
SET_PROPERTY(TARGET G4parmodels APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4parmodels PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4processes;G4track"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4parmodels.so"
  IMPORTED_SONAME_RELEASE "libG4parmodels.so"
  )

# Import target "G4particles" for configuration "Release"
SET_PROPERTY(TARGET G4particles APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4particles PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4global;G4materials;G4geometry;G4intercoms"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4particles.so"
  IMPORTED_SONAME_RELEASE "libG4particles.so"
  )

# Import target "G4persistency" for configuration "Release"
SET_PROPERTY(TARGET G4persistency APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4persistency PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4digits_hits;G4event;G4run;G4track;G4tracking"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4persistency.so"
  IMPORTED_SONAME_RELEASE "libG4persistency.so"
  )

# Import target "G4physicslists" for configuration "Release"
SET_PROPERTY(TARGET G4physicslists APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4physicslists PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4geometry;G4global;G4intercoms;G4materials;G4particles;G4processes;G4run;G4track;G4digits_hits;G4event;G4tracking"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4physicslists.so"
  IMPORTED_SONAME_RELEASE "libG4physicslists.so"
  )

# Import target "G4processes" for configuration "Release"
SET_PROPERTY(TARGET G4processes APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4processes PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4geometry;G4global;G4intercoms;G4materials;G4particles;G4track;/usr/lib64/libexpat.so"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4processes.so"
  IMPORTED_SONAME_RELEASE "libG4processes.so"
  )

# Import target "G4readout" for configuration "Release"
SET_PROPERTY(TARGET G4readout APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4readout PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4event;G4geometry;G4global;G4intercoms;G4materials;G4particles;G4processes;G4run;G4track;G4tracking"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4readout.so"
  IMPORTED_SONAME_RELEASE "libG4readout.so"
  )

# Import target "G4run" for configuration "Release"
SET_PROPERTY(TARGET G4run APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4run PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4event;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4processes;G4track;G4tracking"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4run.so"
  IMPORTED_SONAME_RELEASE "libG4run.so"
  )

# Import target "G4track" for configuration "Release"
SET_PROPERTY(TARGET G4track APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4track PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4geometry;G4global;G4intercoms;G4materials;G4particles"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4track.so"
  IMPORTED_SONAME_RELEASE "libG4track.so"
  )

# Import target "G4tracking" for configuration "Release"
SET_PROPERTY(TARGET G4tracking APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4tracking PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4processes;G4track"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4tracking.so"
  IMPORTED_SONAME_RELEASE "libG4tracking.so"
  )

# Import target "G4FR" for configuration "Release"
SET_PROPERTY(TARGET G4FR APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4FR PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4modeling;G4vis_management"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4FR.so"
  IMPORTED_SONAME_RELEASE "libG4FR.so"
  )

# Import target "G4visHepRep" for configuration "Release"
SET_PROPERTY(TARGET G4visHepRep APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4visHepRep PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4modeling;G4tracking;G4vis_management;G4zlib"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4visHepRep.so"
  IMPORTED_SONAME_RELEASE "libG4visHepRep.so"
  )

# Import target "G4RayTracer" for configuration "Release"
SET_PROPERTY(TARGET G4RayTracer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4RayTracer PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4event;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4modeling;G4particles;G4processes;G4track;G4tracking;G4vis_management;/usr/lib64/libSM.so;/usr/lib64/libICE.so;/usr/lib64/libX11.so;/usr/lib64/libXext.so"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4RayTracer.so"
  IMPORTED_SONAME_RELEASE "libG4RayTracer.so"
  )

# Import target "G4Tree" for configuration "Release"
SET_PROPERTY(TARGET G4Tree APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4Tree PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4modeling;G4particles;G4track;G4vis_management"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4Tree.so"
  IMPORTED_SONAME_RELEASE "libG4Tree.so"
  )

# Import target "G4VRML" for configuration "Release"
SET_PROPERTY(TARGET G4VRML APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4VRML PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4modeling;G4vis_management"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4VRML.so"
  IMPORTED_SONAME_RELEASE "libG4VRML.so"
  )

# Import target "G4visXXX" for configuration "Release"
SET_PROPERTY(TARGET G4visXXX APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4visXXX PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4geometry;G4global;G4graphics_reps;G4intercoms;G4modeling;G4tracking;G4vis_management"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4visXXX.so"
  IMPORTED_SONAME_RELEASE "libG4visXXX.so"
  )

# Import target "G4gl2ps" for configuration "Release"
SET_PROPERTY(TARGET G4gl2ps APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4gl2ps PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4zlib;/usr/lib64/libGLU.so;/usr/lib64/libGL.so;/usr/lib64/libSM.so;/usr/lib64/libICE.so;/usr/lib64/libX11.so;/usr/lib64/libXext.so"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4gl2ps.so"
  IMPORTED_SONAME_RELEASE "libG4gl2ps.so"
  )

# Import target "G4zlib" for configuration "Release"
SET_PROPERTY(TARGET G4zlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4zlib PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4zlib.so"
  IMPORTED_SONAME_RELEASE "libG4zlib.so"
  )

# Import target "G4GMocren" for configuration "Release"
SET_PROPERTY(TARGET G4GMocren APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4GMocren PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4FR;G4digits_hits;G4event;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4modeling;G4particles;G4tracking;G4vis_management"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4GMocren.so"
  IMPORTED_SONAME_RELEASE "libG4GMocren.so"
  )

# Import target "G4vis_management" for configuration "Release"
SET_PROPERTY(TARGET G4vis_management APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4vis_management PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4event;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4modeling;G4particles;G4processes;G4run;G4track;G4tracking"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4vis_management.so"
  IMPORTED_SONAME_RELEASE "libG4vis_management.so"
  )

# Import target "G4modeling" for configuration "Release"
SET_PROPERTY(TARGET G4modeling APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4modeling PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4event;G4geometry;G4global;G4graphics_reps;G4intercoms;G4materials;G4particles;G4processes;G4track;G4tracking"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4modeling.so"
  IMPORTED_SONAME_RELEASE "libG4modeling.so"
  )

# Import target "G4OpenGL" for configuration "Release"
SET_PROPERTY(TARGET G4OpenGL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(G4OpenGL PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4digits_hits;G4geometry;G4gl2ps;G4global;G4graphics_reps;G4intercoms;G4interfaces;G4modeling;G4tracking;G4vis_management;/usr/lib64/libGLU.so;/usr/lib64/libGL.so;/usr/lib64/libSM.so;/usr/lib64/libICE.so;/usr/lib64/libX11.so;/usr/lib64/libXext.so;/usr/lib64/libXmu.so;/usr/lib64/libQtOpenGL.so;/usr/lib64/libQtGui.so;/usr/lib64/libQtGui_debug.so;/usr/lib64/libQtCore.so;/usr/lib64/libQtCore_debug.so"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/external/geant4/geant4_9_6_p02/build/outputs/library/Linux-g++/libG4OpenGL.so"
  IMPORTED_SONAME_RELEASE "libG4OpenGL.so"
  )

# Import target "GamosUtils" for configuration "Release"
SET_PROPERTY(TARGET GamosUtils APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(GamosUtils PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "G4geometry;G4global;G4intercoms;G4materials;G4particles;G4track;G4graphics_reps"
  IMPORTED_LOCATION_RELEASE "/home/arce/gamos/GAMOS.5.0.0/lib/Linux-g++/libGamosUtils.so"
  IMPORTED_SONAME_RELEASE "libGamosUtils.so"
  )


# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
